# Generated by Django 2.2 on 2021-04-13 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0002_user_profile_pic'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='profile_pic',
            field=models.ImageField(upload_to='blog/%Y/%m/%d'),
        ),
    ]
