# Generated by Django 2.2 on 2021-04-15 03:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0005_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='bio',
            field=models.TextField(default='Please update your bio'),
        ),
        migrations.AddField(
            model_name='user',
            name='website',
            field=models.TextField(default='N/A'),
        ),
    ]
