# Generated by Django 2.2 on 2021-04-16 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0007_auto_20210414_2101'),
    ]

    operations = [
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField()),
                ('linkedin', models.TextField()),
                ('instagram', models.TextField()),
                ('twitter', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user_media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_social_media', to='Solo_Project_App.User')),
            ],
        ),
    ]
