# Generated by Django 2.2 on 2021-04-16 06:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0008_media'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='facebook',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='media',
            name='instagram',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='media',
            name='linkedin',
            field=models.TextField(default='N/A'),
        ),
        migrations.AlterField(
            model_name='media',
            name='twitter',
            field=models.TextField(default='N/A'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_ordered', models.IntegerField(default=1)),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('portfolio_order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portfolio_item_ordered', to='Solo_Project_App.Portfolio')),
            ],
        ),
    ]
