# Generated by Django 2.2 on 2021-04-16 07:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0009_auto_20210415_2322'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='portfolio_item',
            field=models.ManyToManyField(related_name='all_portfolio_items', to='Solo_Project_App.User'),
        ),
        migrations.AlterField(
            model_name='order',
            name='portfolio_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_portfolio_order', to='Solo_Project_App.User'),
        ),
    ]
