# Generated by Django 2.2 on 2021-04-17 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0011_auto_20210416_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='portfolio_order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_of_portfolio', to='Solo_Project_App.Portfolio'),
        ),
    ]
