# Generated by Django 2.2 on 2021-04-17 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0013_cart'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='quantity',
        ),
    ]
