# Generated by Django 2.2 on 2021-04-18 02:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0018_auto_20210417_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='user_cart',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='cart_of_user', to='Solo_Project_App.User'),
        ),
    ]
