# Generated by Django 2.2 on 2021-04-18 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0020_cart_item_added'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_added',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='item_added',
            field=models.ManyToManyField(related_name='user_items', to='Solo_Project_App.Cart'),
        ),
    ]
