# Generated by Django 2.2 on 2021-04-20 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0024_auto_20210419_2231'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='website',
            field=models.TextField(),
        ),
    ]
