# Generated by Django 2.2 on 2021-04-23 23:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Solo_Project_App', '0029_auto_20210423_1612'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='user',
        ),
    ]
